### ISSUE TITLE
Getting error with installion fo ai payemnt

### ISSUE THREAD

**Issue by bhazboun123** [aimeoscom/ai-payments#10]
I have aimeos laravel installed and I have this in my composer.json:

"aimeos/aimeos-laravel": "~2017.04",
"aimeos/ai-payments": "dev-master"

and I am getting this error : 

- Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.11].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.1].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.10].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.11].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.2].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.3].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.4].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.5].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.6].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.7].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.8].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.9].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.x-dev].

I am not sure which one I need to install that will work?

Thanks

**Comment by aimeos** [comment]
Both must fit together, so if you have to use ~2017.04 for both packages

**Comment by bhazboun123** [comment]
great thanks that worked
