### ISSUE TITLE
Stripe Error payment form.

### ISSUE THREAD

**Issue by Nanard** [aimeoscom/ai-payments#14]
I get this js error when loading payment form.

To fix the error I have to modify Stipe.php and change in $feConfig : 
payment.cardno => payment-cardno
payment.expiry => payment-expiry
payment.cvv => payment-cvv

Maybe someone can test and fix it for the next release.

![capture d ecran 2018-11-14 a 09 42 38](https://user-images.githubusercontent.com/500045/48470472-ce5aec80-e7f1-11e8-9f8a-619bb8893037.png)

**Comment by aimeos** [comment]
Are you able to create a PR with the necessary changes?

**Comment by Nanard** [comment]
Done

**Comment by Nanard** [comment]
When will it be released ?

**Comment by aimeos** [comment]
New release has been tagged now :-)
