### ISSUE TITLE
Token Selector not Working

### ISSUE THREAD

**Issue by tenkraD** [aimeoscom/ai-payments#18]
https://github.com/aimeoscom/ai-payments/blob/84ec67dcb49f27881c609c61c185dac615036a2b/lib/custom/src/MShop/Service/Provider/Payment/Stripe.php#L240

This works.
`token_selector: "input[name=\"ai[paymenttoken]\"]",`

**Comment by aimeos** [comment]
Thank you for your hint! We are now using the ID because it doesn't depend on the environment:
https://github.com/aimeoscom/ai-payments/commit/3cae877c72b8376dca460c4a57d76e1847c72124

Can you check if that works? If yes, we will backport it to the 2018.10 branch too and make a new release.

**Comment by tenkraD** [comment]
No it doesn't work with the id.
The hidden Field in Template for the token has no ID just a name Attribute.

**Comment by aimeos** [comment]
Can you please post the HTML that is generated?

**Comment by tenkraD** [comment]
`<input type="hidden" name="ai[paymenttoken]" value="">`

**Comment by aimeos** [comment]
With this change in the template it should work now: https://github.com/aimeos/ai-client-html/commit/caedc320033814f0fde095b0ec7c5b4ef6e1bad6

**Comment by tenkraD** [comment]
ok with changing the template selecting over id works. 

but i dont understand how `token_selector: "input[name=\"ai[paymenttoken]\"]",`
should depend on the enviroment. issue can be closed

**Comment by aimeos** [comment]
TYPO3: name="ai[paymenttoken]"
Other frameworks: name="paymenttoken"
