### ISSUE TITLE
Mount the stripe JS Elements to a div

### ISSUE THREAD

**Issue by tenkraD** [aimeoscom/ai-payments#19]
https://github.com/aimeos/ai-client-html/commit/ab2314b3ba722377164157464e5a7aef150a348d
https://github.com/tenkraD/ai-payments/commit/d8145afe0019bc52bcf973745be8ce00500f5de2

**Comment by aimeos** [comment]
Can you please turn this two commits into pull requests (create pull request button)?

**Comment by tenkraD** [comment]
Pull request creation failed. Validation failed: You can't perform that action at this time.

**Comment by aimeos** [comment]
Make sure the aimeos/aimeoscom repo is selected as base
