### ISSUE TITLE
Call to undefined method Omnipay\Quickpay\Message\Notification::send()

### ISSUE THREAD

**Issue by mahrezo** [aimeoscom/ai-payments#30]
I'm using Aimeos extension v19.10.1 with TYPO3 9.5.14 ... I setup the payment gateway to connect my shop with Quickpay Driver, evreyhting is okay except the payment confirmation.

Even the payment approved on my Quickpay account and the amount  deducted from the credit card, on my site still I have the following message : _Payment status : unfinished_

by launching callbackurl I get : 

    Call to undefined method Omnipay\Quickpay\Message\Notification::send()
    in /var/www/example.com/typo3conf/ext/aimeos_pay/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/OmniPay.php line 504

**Comment by mahrezo** [comment]
Using the Aimeos extension version 20.10.6 for TYPO3 v9.5.24 and without the 'aimeos_pay' extension
```
"aimeos/ai-payments": "^2020.10",
"nobrainerweb/omnipay-quickpay": "^3.0"
```

Give the same error : Screenshot : https://i.ibb.co/Jq3gLwd/eror.jpg

**Comment by aimeos** [comment]
Sorry for the late reply. We've changed the code in the Omnipay driver a few days after your comment but didn't notice you about the change: https://github.com/aimeoscom/ai-payments/commit/82ac32ba98237c1ab62b8e36e0e76db7b74750fd#diff-1ade37ae74897234ff1304f4e04e8bda6d3563d3ac8fed3f452d7ce26f3c9c51

The change is now also in 2020.10.x and you can test it using:
```
composer req aimeos/ai-payments:2020.10.x-dev
```
