### ISSUE TITLE
require aimeos in composer.json

### ISSUE THREAD

**Issue by pide2000** [aimeoscom/ai-payments#4]
Hey there,

I think in the composer.json "aimeos/aimeos-core" should be required. The ai-payments package is, in my opinion, just usable with aimeos, since it is an extension for aimeos. 

My current problem is,  the installation of ai-payments throws an exception, because aimeos is installed after ai-payments so the folder to install ai-payments into is simply not present. The Solution above would fix this problem. 

As an hint: I have a global composer.json which installs the whole aimeos stuff. ai-payments is installed to the correct place by providing an "installer-path". I don't touch the composer.json which ships with the "aimeos-core"

So thank you in advance 
P

**Comment by aimeos** [comment]
Thank you for the hint. The release version already had this requirement but in dev-master it was missing. This should be fixed now. Can you confirm?
