### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by peteracs** [aimeoscom/ai-payments#7]
I am using Aimeos laravel and I can't install Ai payments.

Here's the error

Problem 1
    - Conclusion: don't install aimeos/ai-payments 2017.01.2
    - Conclusion: don't install aimeos/ai-payments 2017.01.x-dev
    - Can only install one of: aimeos/aimeos-core[dev-master, 2016.10.7].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2016.10.7].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2016.10.7].
    - aimeos/ai-payments 2017.01.1 requires aimeos/aimeos-core dev-master -> satisfiable by aimeos/aimeos-core[dev-master].
    - Installation request for aimeos/ai-payments ^2017.01 -> satisfiable by aimeos/ai-payments[2017.01.1, 2017.01.2, 2017.01.x-dev].
    - Installation request for aimeos/aimeos-core == 2016.10.7.0 -> satisfiable by aimeos/aimeos-core[2016.10.7].

I guess it's because of aimeos-core is required ?

**Comment by aimeos** [comment]
You mixed up version. If you use aimeos-core 2016.10 (used by aimeos/aimeos-laravel 2016.10 and all other integrations), you have to use aimeoscom/ai-payments 2016.10 as well (not 2017.01)

**Comment by peteracs** [comment]
Right, using 2016.10 solved it! Thanks
